name: Autograding Tests

on:
  push:
  workflow_dispatch:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 用官方 Python，不要 miniconda 路径
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install clingo
        run: |
          python -m pip install --upgrade pip
          pip install "clingo==5.7.1"

      # ---- 评分项 ----
      - name: Question 0a
        id: question-0a
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "Question 0a: group.txt exists"
          command: 'ls group.txt'
          timeout: '30'
          max-score: '5'

      - name: Question 0b
        id: question-0b
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "Question 0b: group.txt is not empty"
          command: 'ls group.txt && [ -s group.txt ]'
          timeout: '30'
          max-score: '5'

      - name: Question 1a
        id: question-1a
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "Question 1a"
          setup-command: ''
          command: 'ls group.txt && [ -s group.txt ] && python autograder.py --clingo clingo --question=1a'
          timeout: '180'
          max-score: '25'

      - name: Question 1b
        id: question-1b
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "Question 1b"
          setup-command: ''
          command: 'ls group.txt && [ -s group.txt ] && python autograder.py --clingo clingo --question=1b'
          timeout: '180'
          max-score: '15'

      - name: Question 1c
        id: question-1c
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "Question 1c"
          setup-command: ''
          command: 'ls group.txt && [ -s group.txt ] && python autograder.py --clingo clingo --question=1c'
          timeout: '180'
          max-score: '15'

      - name: Question 2
        id: question-2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "Question 2"
          setup-command: ''
          command: 'ls group.txt && [ -s group.txt ] && python autograder.py --clingo clingo --question=2'
          timeout: '300'
          max-score: '35'

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          QUESTION-0A_RESULTS: "${{steps.question-0a.outputs.result}}"
          QUESTION-0B_RESULTS: "${{steps.question-0b.outputs.result}}"
          QUESTION-1A_RESULTS: "${{steps.question-1a.outputs.result}}"
          QUESTION-1B_RESULTS: "${{steps.question-1b.outputs.result}}"
          QUESTION-1C_RESULTS: "${{steps.question-1c.outputs.result}}"
          QUESTION-2_RESULTS:  "${{steps.question-2.outputs.result}}"
        with:
          runners: 'question-0a,question-0b,question-1a,question-1b,question-1c,question-2'
